### ISSUE TITLE
honeymap.js is missing from /honeymap/client/js

### ISSUE THREAD

**Issue by honeymap** [fw42/honeymap#10]
just a heads up --  /honeymap/client/index.html references a honeymap.js file that should reside in /honeymap/client/js.  however, in the github source, it looks like it is missing.

**Comment by heipei** [comment]
Did you read anything from the README? Honeymap is written in CoffeeScript, youll have to compile it to JavaScript using "make" in folder "honeynet"

**Comment by honeymap** [comment]
i followed the directions, but did not compile.  ill try again.

**Comment by honeymap** [comment]
ah -- i see where things went south.

Thank you for pointing out the obvious.
